### ISSUE TITLE
How to specify a genomic alteration caused by a concurrent deletion and inseriton. 

### ISSUE THREAD

**Issue by Haldrup** [uzh-dqbm-cmi/PRIDICT#3]
Hi,

I've encountered an issue for pegRNA design of SFTPB121ins as this specific mutation is caused by a concurrent deletion and insertion at the same position. I have provided the sequence below including 110 bp flanking regions. The aim is to correct the disease-variant "gaa" to the wild-type 'c".   

GGCCAAGGAGGCCATTTTCCAGGACACGATGAGGAAGTTCCTGGAGCAGGAGTGCAACGTCCTCCCCTTGAAGCTGCTCATGCCCCAGTGCAACCAAGTGCTTGACGACTACTTC(gaa/c)CCCTGGTCATCGACTACTTCCAGAACCAGACTGACTCAAACGGCATCTGTATGCACCTGGGCCTGTGCAAATCCCGGCAGCCAGAGCCAGAGCAGGAGCCAGGGATGTCA

I am unfortunately unable to queue the above as "replacement".

Any easy fix for this type of mutation?

Thanks
Jakob

**Comment by mathinic** [comment]
Hi Jakob

Unfortunately PRIDICT is only able to predict insertions, deletions ***or*** replacements (of same size before/after).
This is because the training set does not include such combination-edits since the complexity of such a dataset would be several times higher than for same-sized replacements.

However, as a workaround, you could try using PRIDICT to design a pegRNA for a similar edit (e.g. replacing 'GAA' with 'TAC'), and then manually adjust the pegRNA to make the desired 'GAA' to 'C' change (remove TA from the RTT; example below). This method isn’t perfect, but it could help you rule out unsuitable pegRNAs, like those with polyT stretches. Please note that the reliability of the scores may vary for the manually modified pegRNA.

Best,
Nicolas

`GGCCAAGGAGGCCATTTTCCAGGACACGATGAGGAAGTTCCTGGAGCAGGAGTGCAACGTCCTCCCCTTGAAGCTGCTCATGCCCCAGTGCAACCAAGTGCTTGACGACTACTTC(gaa/tac)CCCTGGTCATCGACTACTTCCAGAACCAGACTGACTCAAACGGCATCTGTATGCACCTGGGCCTGTGCAAATCCCGGCAGCCAGAGCCAGAGCAGGAGCCAGGGATGTCA`
